### ISSUE TITLE
OSError: libcusparse.so.11: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by divyavani-d** [yazdanimehdi/FragXsiteDTI#1]
Traceback (most recent call last):
  File "/home/ubuntu/Divya/FragXsiteDTI/main.py", line 10, in <module>
    from dataset import collate_wrapper
  File "/home/ubuntu/Divya/FragXsiteDTI/dataset.py", line 4, in <module>
    import dgl
  File "/home/ubuntu/anaconda3/envs/fragx/lib/python3.11/site-packages/dgl/__init__.py", line 14, in <module>
    from .backend import backend_name, load_backend  # usort: skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/fragx/lib/python3.11/site-packages/dgl/backend/__init__.py", line 122, in <module>
    load_backend(get_preferred_backend())
  File "/home/ubuntu/anaconda3/envs/fragx/lib/python3.11/site-packages/dgl/backend/__init__.py", line 51, in load_backend
    from .._ffi.base import load_tensor_adapter  # imports DGL C library
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/fragx/lib/python3.11/site-packages/dgl/_ffi/base.py", line 50, in <module>
    _LIB, _LIB_NAME, _DIR_NAME = _load_lib()
                                 ^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/fragx/lib/python3.11/site-packages/dgl/_ffi/base.py", line 39, in _load_lib
    lib = ctypes.CDLL(lib_path[0])
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/anaconda3/envs/fragx/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libcusparse.so.11: cannot open shared object file: No such file or directory

**Comment by yazdanimehdi** [comment]
Hello,
I think it is an issue with your DGL package installation.
Please try removing the package and install it this way:
```bash
pip install dgl -f https://data.dgl.ai/wheels/repo.html
```
Also you can use the DeepDrugDomain as well:
https://github.com/yazdanimehdi/DeepDrugDomain
